"""Add justification and CAPA to regulatory impact

Revision ID: 35fd2d3504c7
Revises: d541964abd0b
Create Date: 2026-05-19 00:12:55.644089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '35fd2d3504c7'
down_revision: Union[str, None] = 'd541964abd0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regulatory_impacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('impact_justification', sa.Text(), server_default='', nullable=False))
        batch_op.add_column(sa.Column('capa_recommendations', sa.Text(), server_default='[]', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regulatory_impacts', schema=None) as batch_op:
        batch_op.drop_column('capa_recommendations')
        batch_op.drop_column('impact_justification')

    # ### end Alembic commands ###
