"""Add phone to user

Revision ID: 49765a66292e
Revises: a0abef686669
Create Date: 2026-04-23 22:35:48.203817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '49765a66292e'
down_revision: Union[str, None] = 'a0abef686669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
