"""Add Regulatory Watch models

Revision ID: 55444d484004
Revises: ff6f97c31191
Create Date: 2026-05-14 19:44:53.507513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '55444d484004'
down_revision: Union[str, None] = 'ff6f97c31191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regulatory_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('source_type', sa.Enum('rss', 'api', 'scrape', name='regulatory_source_type'), nullable=False),
    sa.Column('parser_name', sa.String(length=255), nullable=False),
    sa.Column('frequency_hours', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regulatory_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('publication_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('original_url', sa.String(length=1024), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('extracted_requirements', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='severity_level'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['regulatory_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_regulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('regulation_name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_regulations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_regulations_project_id'), ['project_id'], unique=False)

    op.create_table('regulatory_impacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('update_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('impact_summary', sa.Text(), nullable=False),
    sa.Column('impacted_areas', sa.Text(), nullable=False),
    sa.Column('suggested_actions', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_review', 'addressed', name='regulatory_impact_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['update_id'], ['regulatory_updates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('regulatory_impacts')
    with op.batch_alter_table('project_regulations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_regulations_project_id'))

    op.drop_table('project_regulations')
    op.drop_table('regulatory_updates')
    op.drop_table('regulatory_sources')
    # ### end Alembic commands ###
