"""add_compliance_fields_to_gap_analysis_item

Revision ID: 985768f6035c
Revises: d02c752aad72
Create Date: 2026-05-19 17:14:41.008815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '985768f6035c'
down_revision: Union[str, None] = 'd02c752aad72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gap_analysis_items', sa.Column('compliance_score', sa.Integer(), nullable=True))
    op.add_column('gap_analysis_items', sa.Column('compliance_status', sa.String(length=50), nullable=True))
    op.execute("UPDATE gap_analysis_items SET compliance_score = 100, compliance_status = 'Conforme'")
    op.alter_column('gap_analysis_items', 'compliance_score', nullable=False)
    op.alter_column('gap_analysis_items', 'compliance_status', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gap_analysis_items', schema=None) as batch_op:
        batch_op.drop_column('compliance_status')
        batch_op.drop_column('compliance_score')

    # ### end Alembic commands ###
