"""Add recovery code to user

Revision ID: a0abef686669
Revises: de7a85be358e
Create Date: 2026-04-23 22:28:51.641073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a0abef686669'
down_revision: Union[str, None] = 'de7a85be358e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recovery_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('recovery_code_expires_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('recovery_code_expires_at')
        batch_op.drop_column('recovery_code')

    # ### end Alembic commands ###
