"""add progress column

Revision ID: d008f4b5efd9
Revises: 49765a66292e
Create Date: 2026-04-24 16:41:04.589647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd008f4b5efd9'
down_revision: Union[str, None] = '49765a66292e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress', sa.Integer(), server_default='0', nullable=False))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('progress')

    with op.batch_alter_table('processes', schema=None) as batch_op:
        batch_op.drop_column('progress')

    # ### end Alembic commands ###
