"""Add GapAnalysis and Capa models

Revision ID: d02c752aad72
Revises: 35fd2d3504c7
Create Date: 2026-05-19 01:18:50.463339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd02c752aad72'
down_revision: Union[str, None] = '35fd2d3504c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('capas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_capas_project_id'), ['project_id'], unique=False)

    op.create_table('gap_analysis_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('target_standards', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gap_analysis_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gap_analysis_reports_project_id'), ['project_id'], unique=False)

    op.create_table('gap_analysis_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('document_title', sa.String(length=255), nullable=False),
    sa.Column('missing_clauses', sa.Text(), nullable=False),
    sa.Column('update_suggestions', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['gap_analysis_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gap_analysis_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gap_analysis_items_report_id'), ['report_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gap_analysis_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gap_analysis_items_report_id'))

    op.drop_table('gap_analysis_items')
    with op.batch_alter_table('gap_analysis_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gap_analysis_reports_project_id'))

    op.drop_table('gap_analysis_reports')
    with op.batch_alter_table('capas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capas_project_id'))

    op.drop_table('capas')
    # ### end Alembic commands ###
