"""Add standards and procedures to regulatory impact

Revision ID: d541964abd0b
Revises: 55444d484004
Create Date: 2026-05-18 23:50:43.820810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd541964abd0b'
down_revision: Union[str, None] = '55444d484004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regulatory_impacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('standards_updated', sa.Text(), server_default='[]', nullable=False))
        batch_op.add_column(sa.Column('procedures_impacted', sa.Text(), server_default='[]', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regulatory_impacts', schema=None) as batch_op:
        batch_op.drop_column('procedures_impacted')
        batch_op.drop_column('standards_updated')

    # ### end Alembic commands ###
