"""Add message hiding support

Revision ID: de7a85be358e
Revises: 6c5c197b7192
Create Date: 2026-04-23 21:57:30.679067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'de7a85be358e'
down_revision: Union[str, None] = '6c5c197b7192'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_hidden',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', name='uq_msg_user_hidden')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_hidden')
    # ### end Alembic commands ###
