"""add is_validated to projects

Revision ID: fc2a02512030
Revises: d008f4b5efd9
Create Date: 2026-04-24 16:52:39.967119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fc2a02512030'
down_revision: Union[str, None] = 'd008f4b5efd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_email_key', type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('users_email_key', ['email'])

    # ### end Alembic commands ###
