"""add_session_id_to_chat

Revision ID: ff6f97c31191
Revises: 5843e28a5ebd
Create Date: 2026-05-03 00:19:02.535754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ff6f97c31191'
down_revision: Union[str, None] = '5843e28a5ebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.String(length=50), server_default='default', nullable=False))
        batch_op.create_index(batch_op.f('ix_chat_messages_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_session_id'))
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###
